- name: "type:feature"
  color: "0E8A16"
  description: "New feature work"
- name: "type:bug"
  color: "D73A4A"
  description: "Bug fix work"
- name: "type:chore"
  color: "5319E7"
  description: "Maintenance and docs work"
- name: "type:docs"
  color: "1D76DB"
  description: "Documentation changes"
- name: "type:ci"
  color: "BFD4F2"
  description: "CI and automation changes"
- name: "status:triage"
  color: "FBCA04"
  description: "Needs scoping and prioritization"
- name: "status:ready"
  color: "0052CC"
  description: "Ready for implementation"
- name: "priority:high"
  color: "B60205"
  description: "High priority item"
- name: "area:agents"
  color: "0E8A16"
  description: "Agent and skill related changes"
- name: "area:pr-workflow"
  color: "C5DEF5"
  description: "PR workflow wrappers and policy changes"
